---
- hosts: localhost
  tasks:
  - name: Install packages
    become: true
    apt:
      pkg:
      - yamllint
      - htop
  - name: Add a setting to ~/.gitconfig
    community.general.git_config:
      name: user.name
      scope: global
      value: Axel Uhlig
