---
- hosts: localhost
  tasks:
  - name: Install packages
    become: true
    apt:
      pkg:
      - yamllint
      - htop
      - repo
  - name: Create src directory
    file:
      path: ~/src
      state: directory
  - name: Add a setting to ~/.gitconfig
    community.general.git_config:
      name: user.name
      scope: global
      value: Axel Uhlig
  - name: Add a setting to ~/.gitconfig
    community.general.git_config:
      name: user.email
      scope: global
      value: axel.uhlig@gmail.com
