---
- hosts: localhost
  tasks:
  - name: Install packages prep
    become: true
    apt:
      pkg:
      - apt-transport-https
      - ca-certificates
      - gnupg-agent
      - software-properties-common
  - name: Add Docker’s official GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  - name: Install packages
    become: true
    update_cache: yes
    apt:
      pkg:
      - yamllint
      - htop
      - zsh
      - silversearcher-ag
      - python3-pip
      - docker-ce 
      - docker-ce-cli 
      - containerd.io
  - name: Create src directory
    file:
      path: ~/src
      state: directory
  - name: Clone git repo - workspace
    git:
      repo: 'https://github.com/axeluhlig/workstation_setup.git'
      dest: ~/src/workstation_setup
  - name: Clone git repo - github_to_elastic_search
    git:
      repo: https://github.com/axeluhlig/github_to_elastic_search.git
      dest: ~/src/github_to_elastic_search
  - name: git user name
    community.general.git_config:
      name: user.name
      scope: global
      value: Axel Uhlig
  - name: git mail
    community.general.git_config:
      name: user.email
      scope: global
      value: axel.uhlig@gmail.com
  - name: git editor
    community.general.git_config:
      name: core.editor
      scope: global
      value: vim
  - name: Installing Oh My Zsh
    ignore_errors: yes
    shell:
      cmd: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      chdir: ~
  - name: Set zsh theme
    lineinfile:
      path: ~/.zshrc
      regexp: '^ZSH_THEME='
      line: ZSH_THEME=jnrowe
  - name: Activate ansible color 
    lineinfile:
      path: ~/.zshrc
      regexp: '^export ANSIBLE_FORCE_COLOR='
      line:  export ANSIBLE_FORCE_COLOR=true
