---
- hosts: localhost
  tasks:
  - name: Install packages
    become: true
    apt:
      pkg:
      - yamllint
      - htop
  - name: Create src directory
    file:
      path: ~/src
      state: directory
  - name: Clone git repo - workspace
    git:
      repo: 'https://github.com/axeluhlig/workstation_setup.git'
      dest: /src/workstation_setup
  - name: Add a setting to ~/.gitconfig
    community.general.git_config:
      name: user.name
      scope: global
      value: Axel Uhlig
  - name: Add a setting to ~/.gitconfig
    community.general.git_config:
      name: user.email
      scope: global
      value: axel.uhlig@gmail.com
